/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "meatpriceapi",
            "endpoint": "https://gykqnetutd.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "meatpricedb-prod",
            "region": "us-east-1"
        },
        {
            "tableName": "customerorderdb-prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "theranch-20220207171542-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d34mep5zcaxfxz.cloudfront.net"
};


export default awsmobile;
