/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5o4t5qkmhvhqddp3dj7yoravxa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2iq5s5eyzfehdm2gxzzrgzumre",
    "aws_cloud_logic_custom": [
        {
            "name": "meatpriceapi",
            "endpoint": "https://gykqnetutd.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "meatpricedb-prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
